import type { Product, CustomerMessage } from '@/types';

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-adire-peplum-harem',
    name: 'Adire Crepe Top and Denim Adire Trouser',
    description: 'Premium green-and-white patterned Adire crepe peplum top paired with stylish, vibrant pink tie-dye harem-style denim trousers.',
    price: 45000,
    category: 'adire',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Green & Pink'],
    images: ['/images/green_pink_set.jpg'],
    stock: 12,
    featured: true,
    createdAt: new Date('2026-08-20'),
  },
  {
    id: 'demo-adire-crepe-2pcs',
    name: 'Adire Crepe 2pcs Set',
    description: 'Sophisticated terracotta red two-piece coord set featuring wide-leg pants and a loose wrap-style kimono top in a rich cultural pattern.',
    price: 45000,
    category: 'adire',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Terracotta Red'],
    images: ['/images/terracotta_coord.jpg'],
    stock: 8,
    featured: true,
    createdAt: new Date('2026-08-21'),
  },
  {
    id: 'demo-adire-handkerchief-skirt',
    name: 'Adire Crepe Handkerchief Skirt with Top',
    description: 'Chic tie-dye co-ord set featuring a flared handkerchief skirt paired with a matching crop top in a beautiful red and white dye print.',
    price: 35000,
    category: 'adire',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Red & White'],
    images: ['/images/red_layered_skirt.jpg'],
    stock: 15,
    featured: true,
    createdAt: new Date('2026-08-22'),
  },
  {
    id: 'demo-adire-wrap-skirt',
    name: 'Adire Crepe Top and Denim Adire Skirt',
    description: 'Vibrant yellow-gold long sleeve wrap top paired with a layered green-and-white patterned Adire tiered denim mini skirt.',
    price: 40000,
    category: 'adire',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Yellow & Green'],
    images: ['/images/yellow_green_wrap.jpg'],
    stock: 5,
    featured: true,
    createdAt: new Date('2026-08-23'),
  },
  {
    id: 'demo-adire-caribbean-skirt',
    name: 'Adire Crepe Caribbean Skirt',
    description: 'Stunning multi-colored tiered maxi Caribbean skirt displaying blocks of red, blue, yellow, and white traditional Adire patterns.',
    price: 30000,
    category: 'adire',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Multi-color'],
    images: ['/images/caribbean_skirt.jpg'],
    stock: 14,
    featured: false,
    createdAt: new Date('2026-08-24'),
  },
  {
    id: 'demo-adire-jumpsuit',
    name: 'Adire Crepe Jumpsuit',
    description: 'Elegant halter-neck wide-leg jumpsuit crafted in deep burgundy and white Adire patterns with a cinched elastic waist.',
    price: 38000,
    category: 'adire',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Burgundy & White'],
    images: ['/images/halter_jumpsuit.jpg'],
    stock: 9,
    featured: false,
    createdAt: new Date('2026-08-25'),
  },
  {
    id: 'demo-adire-boubou-orange',
    name: 'Adire Crepe 2in1 Backless Boubou Gown (Orange)',
    description: 'Flowy orange-and-white patterned boubou gown featuring a backless drape design, complete with a matching custom bralette.',
    price: 38000,
    category: 'adire',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Orange & White'],
    images: ['/images/orange_boubou.jpg'],
    stock: 11,
    featured: false,
    createdAt: new Date('2026-08-26'),
  },
  {
    id: 'demo-adire-boubou-pink',
    name: 'Adire Crepe 2in1 Backless Boubou Gown (Pink)',
    description: 'Gorgeous pink-and-white patterned boubou gown featuring a dramatic backless drape design and matching custom bralette.',
    price: 38000,
    category: 'adire',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Pink & White'],
    images: ['/images/pink_boubou.jpg'],
    stock: 10,
    featured: false,
    createdAt: new Date('2026-08-27'),
  },
  // Handwoven Aso Oke Collections
  {
    id: 'demo-asooke-short',
    name: 'Aso Oke Short',
    description: 'Modern luxury handwoven striped Aso Oke shorts featuring front cargo pockets, an adjustable elastic drawstring waistband, and signature cultural tailoring.',
    price: 25000,
    category: 'asooke',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Navy & Burgundy Stripe'],
    images: ['/images/asooke_short.jpg'],
    stock: 15,
    featured: true,
    createdAt: new Date('2026-09-25'),
  }
];

export const DEMO_MESSAGES: CustomerMessage[] = [
  {
    id: 'demo-msg-1',
    name: 'Olumide Bakare',
    email: 'olumide@example.com',
    phone: '+234 803 111 2222',
    subject: 'Bespoke Agbada Measurement Details',
    message: 'Hello, I just placed an order and wanted to attach my custom measurements for the Tunmise Classic Metallic Asooke Agbada Set. Please let me know if you need any adjustments.',
    type: 'custom_measurement',
    measurements: {
      bust: '38"',
      waist: '32"',
      hips: '41"',
      height: "5'11\"",
      additionalDetails: 'Prefer the trousers to be loose around the ankles.',
    },
    status: 'unread',
    createdAt: new Date('2026-08-27T14:30:00.000Z'),
  },
  {
    id: 'demo-msg-2',
    name: 'Chioma Nnaji',
    email: 'chioma@example.com',
    phone: '+234 812 345 6789',
    subject: 'Custom Gold Thread Request',
    message: 'Hi, is it possible to use rose gold embroidery threads for the Asooke wrappers instead of standard yellow gold? I have an upcoming wedding in December.',
    type: 'bespoke_inquiry',
    status: 'read',
    createdAt: new Date('2026-08-26T09:15:00.000Z'),
  },
  {
    id: 'demo-msg-3',
    name: 'Fatima Yusuf',
    email: 'fatima@example.com',
    phone: '+234 905 555 4444',
    subject: 'Delivery Timeline to Abuja',
    message: 'Hello! If I order the Adire Crepe 2pcs Set today, how many days will it take to arrive in Garki, Abuja?',
    type: 'general',
    status: 'replied',
    createdAt: new Date('2026-08-25T11:00:00.000Z'),
  }
];

